services:

  db:
    build: ./db
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: php
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    volumes:
      - ./save/db:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 8s
      retries: 8

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  php:
    build: php
    environment:
      - APACHE_RUN_USER=www-data
      - passw=php
      - user=php
      - nameDb=php
      - db=db
    depends_on:
      db:
        condition: service_healthy
    working_dir: /var/www/html/
    volumes:
      - ./php:/var/www/html/
      - ./save/uploads:/var/www/html/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php